# E-Commerce Micro Service Configuration
#

# TODO: have different variants for Hybris & Demandware

# Fredhopper Connector
#
fredhopper:
  queryserver:
    url: http://localhost:8180
  adminserver:
    url: http://localhost:8180
  access:
    username:
    password:
  admin:
    username: admin
    password: admin
  imageurl:
    mappings: #http://demo.fredhopper.com/images=/fredhopper-images


# Localization properties
#
localization:
  defaultLocale: en_GB
  locales:
    "en_GB":
      fredhopper-universe: catalog01
      fredhopper-locale: en_GB
      fredhopper-productModelMappings: "name=name;description=description;price=price;thumbnailUrl=_thumburl;primaryImageUrl=_imageurl"
      fredhopper-triggerMappings: "taf:claim:segment=fh_keyword"







